### PR TITLE
Kill jquery

### PR DESCRIPTION
**Pull request by MadaraUchiha**
This PR solves #1. jQuery efficiently terminated.

### CODE REVIEW

**Comment by IonicaBizau** [comment]
Thanks! Pretty cool, however there is a bug: when writing another username:

image

Also, I'd like to have the `@` before the username. 

Another thing is that hovering the pie throws some errors....

**Comment by MadaraUchiha** [comment]
I've fixed the first two. I don't get any errors when hovering the pie. What kind of errors do you get, and what browser are you using?

**Comment by IonicaBizau** [comment]
Working fine in Chromium. In Firefox I still get errors when hovering the pie:

image

**Comment by IonicaBizau** [comment]
Another thing is that the arrow of tooltip is a little bit on the left of the mouse. It should be on the mouse position.

**Comment by MadaraUchiha** [comment]
Corrected. Looks like Firefox borks on .dataset when called on non-HTML elements (WebKit/Blink defines .dataset for Element, while Firefox does it for HTMLElement)

**Comment by IonicaBizau** [comment]
Awesome. The tooltip position is still an issue... After fixing it, I will merge it.

BTW, add yourself in `contributors` array, in `package.json`.

**Comment by MadaraUchiha** [comment]
Done :smile:

**Comment by IonicaBizau** [comment]
Thanks! :+1: :smile: Merged in 1.1.0.

**Pull request merged**
